services:
  # -----------------------------------------------------------
  # CONTENEDOR 1: LA BASE DE DATOS MYSQL
  # -----------------------------------------------------------
  db-servicio:
    image: mysql:8.0
    container_name: mysql_carrito
    environment:
      MYSQL_ROOT_PASSWORD: NuevaClaveMaestraCarrito2026!
      MYSQL_DATABASE: CarroDB
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: NuevaContrasenaSeguraCarrito.2026
    ports:
      - "3309:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_carrito:/var/lib/mysql

  # -----------------------------------------------------------
  # CONTENEDOR 2: EL ENTORNO DE TRABAJO JAVA/SPRING BOOT
  # -----------------------------------------------------------
  workspace-java:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_carrito
    ports:
      - "8083:8083"
    depends_on:
      - db-servicio
    networks:
      - red_interna_proyecto
    command: tail -f /dev/null
    volumes:
      - ./codigo-fuente:/app
    working_dir: /app
    environment:
      - PRODUCTO_URL=http://172.31.81.180:8080
      - DB_HOST=db-servicio
      - DB_NAME=CarroDB
      - DB_USER=desarrollador
      - DB_PASSWORD=NuevaContrasenaSeguraCarrito.2026
  
networks:
  red_interna_proyecto:

volumes:
  persistencia_carrito: